apiVersion: v1
kind: Namespace
metadata:
  name: outsideserver
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: outsideserver
  labels:
    name: nginx
spec:
  imagePullSecrets:
  - name: reg-cred-secret
  containers:
  - name: nginxpod
    image: docker-registry:5000/nginx:v1
    resources:
      limits:
        memory: "300Mi"
        cpu: "500m"
    ports:
      - containerPort: 8843
    volumeMounts:
    - name: rootfsmount
      mountPath: /host
    imagePullPolicy: Always

  volumes:
  - name: rootfsmount
    hostPath:
      path: /
      type: Directory
