apiVersion: v1
kind: ServiceAccount
metadata:
  #he can remote exec into pods
  name: wordpressowner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpressownerrole
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpressownerrolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wordpressownerrole
subjects:
- kind: ServiceAccount
  name: wordpressowner
  namespace: default